# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zae6jCOHNIM7Qg4nxERqFApdTwtKEr-3
"""

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as snp

from google.colab import drive
drive.mount('/content/drive')

vaccine_records=pd.read_csv(r'country_vaccinations.csv')
vaccine_records.head()

vaccine_records.shape

vaccine_records.describe()

for col in vaccine_records.columns:
    print(col)

india=vaccine_records.loc[vaccine_records['country']=='India']

india.head()

india.shape

india['vaccines'].value_counts()

india.isnull().sum()

clean_data=india.dropna()
clean_data.isnull().sum()

clean_data.head()

sub_entries=clean_data[["vaccines","date","total_vaccinations"]]

sub_entries

plt.xlabel("Dates",color='black')
plt.ylabel("Total Vaccinations",color='black')
x=sub_entries["date"]
y=sub_entries["total_vaccinations"]
plt.title("Covid Vaccination Progress of india",color="red")
plt.plot(x,y)
plt.grid()
plt.show()

